
name: Publish to Workers

on:
  push:
    branches: [master]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          curl -X PUT "${{ secrets.URL }}" \
          -H "Authorization: ${{ secrets.BEARER }}" \
          -H "Content-Type: application/javascript" \
          --data "@index.js"
